### ISSUE TITLE
Doc: Update build shield in readme.md

### ISSUE THREAD

**Issue by sarthakpranesh** [sarthakpranesh/Cosmos#26]
The `build` badge in the current [readme](https://github.com/sarthakpranesh/Cosmos/blob/master/readme.md) file points to the old name of the project hence `cosmos.ReactNative` because of which it is not able to retrieve the build status from Travis, as Travis has the updated project name `Cosmos`.

Steps to fix
1. Go to https://shields.io/
2. Select the `build` option
3. Click on Travis(.com) and enter `sarthakpranesh` in user and `Cosmos` in repo,
4. Click on down array and copy the markdown, replace that with the existing `build` badge in the readme, and open a pr

**Comment by ujalak1812** [comment]
@sarthakpranesh I have opened a PR, please review.
